# Generated by Django 6.0.2 on 2026-02-20 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_scientific', models.CharField(blank=True, max_length=200)),
                ('plant_part', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2025)),
            ],
            options={
                'ordering': ['name_ko'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('avg_temperature', models.FloatField()),
                ('avg_rainfall', models.FloatField()),
                ('soil_grade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('annotation_level', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('similarity', models.FloatField(default=0.0)),
                ('qc_status', models.CharField(max_length=20)),
                ('compound_class', models.CharField(blank=True, max_length=100)),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('retention_time', models.FloatField(blank=True, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='core.crop')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
